trigger:
- msm8994-pcie

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'arm'
  buildConfiguration: 'Debug'

steps:
- checkout: self
  submodules: true

- task: VSBuild@1
  displayName: Build solution
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: Publish build artifacts
  inputs:
    pathtoPublish: build/BootShim
    artifactName: MSM8992/MSM8994 UEFI Loader
