trigger:
- msm8994-pcie

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'arm'
  buildConfiguration: 'Debug'

steps:
- checkout: self
  submodules: true

- script: certutil -f -importpfx "C:\Program Files (x86)\Windows Kits\10\Tools\certificates\OEM_Test_Cert_2017.pfx"
  displayName: Install certificate

- task: VSBuild@1
  displayName: Build solution
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
